### ISSUE TITLE
Switching to Matrix for project discussion

### ISSUE THREAD

**Issue by claiire** [magicalraccoon/tootstream#109]
Just wondering if there was any interest in switching away from the current nonfree discussion platform to Matrix, a free, decentralized, federated chat protocol?

**Comment by craigmaloney** [comment]
Is there much project discussion outside of the issues on Github to warrant such a change?

**Comment by claiire** [comment]
There's a channel we use on discord for discussion. I dunno if I'm allowed to invite people or not, I'd have to ask.

**Comment by craigmaloney** [comment]
Ah, wasn't aware of that.

#tootstream on irc.freenode.net is still available.

**Comment by magicalraccoon** [comment]
I'd like to stick with gitter.
