### ISSUE TITLE
Create a proper Python PyPI package

### ISSUE THREAD

**Issue by craigmaloney** [magicalraccoon/tootstream#113]
I'd like tootstream to be available on PyPI so that the latest released version is only a ``pip install tootstream`` away.

This unfortunately will break how the current program is run and I'd like to fix that.

Once the current crop of pull requests are merged and a new release is readied I'd like to take a crack at creating a package for tootstream.

**Comment by claiire** [comment]
This would be very good for usability and accessibility, plus it'd make starting it up it so much quicker and easier.

**Comment by claiire** [comment]
ouotheutnhutohuo

**Comment by craigmaloney** [comment]
#122 is the initial steps for packaging this.

**Comment by craigmaloney** [comment]
Released as 0.2.0rc1. Closing this out. Thanks!
