### ISSUE TITLE
Is it really dateutils?

### ISSUE THREAD

**Issue by ng-0** [magicalraccoon/tootstream#118]
I'm currently packaging tootstream for https://gnu.org/s/guix
and I'm curious wether you really depend on "dateutils" (the very old python package)
or if it's just a typo and references the python-builtin / core-package "dateutil" which is kept up to date.
Similar to https://github.com/halcy/Mastodon.py/issues/63

**Comment by ng-0** [comment]
What I meant is https://github.com/magicalraccoon/tootstream/blob/develop/requirements.txt#L2 and not line 4.

**Comment by craigmaloney** [comment]
I'm not seeing dateutils in the code. Wondering if the requirements file is duplicating requirements from Mastodon.py.

**Comment by craigmaloney** [comment]
This is what I get when I install Mastodon.py by itself:

```
certifi==2017.7.27.1
chardet==3.0.4
fancycompleter==0.7
idna==2.6
Mastodon.py==1.1.0
pdbpp==0.9.1
pep8==1.7.0
Pygments==2.2.0
python-dateutil==2.6.1
pytz==2017.2
requests==2.18.4
six==1.10.0
urllib3==1.22
wmctrl==0.3
```
(My environment also installs pdbpp and pep8 so please ignore those packages / dependencies)

**Comment by craigmaloney** [comment]
I pulled out some of the packages that we were explicitly installing and let Mastodon.py install those instead. It should be cleaner now.

Closing this issue for now.

Thanks!
