### ISSUE TITLE
Direct Message / Content Warning on tooting

### ISSUE THREAD

**Issue by ufa** [magicalraccoon/tootstream#124]
I am missing some features on toot command, specifically the option of "Content Warning" and "Direct Message".
It would be great if tootstream had these.

**Comment by craigmaloney** [comment]
Pull request #104 has some of this implemented, but it currently conflicts with the current codebase. We'll need to fix that up so it can be pulled in.

**Comment by craigmaloney** [comment]
I've created a new pull-request for this. (#128 ). Once this is pulled you'll have a nice interface for adding content warnings and updating the privacy of a toot.

**Comment by ufa** [comment]
Thank you

**Comment by craigmaloney** [comment]
This was merged into the development branch.
