### ISSUE TITLE
Installing via pip

### ISSUE THREAD

**Issue by maiki** [magicalraccoon/tootstream#126]
Pinging @craigmaloney here, to continue [a conversation](https://mastodon.sdf.org/@maiki/1944292) about the new pip package.

I'd love to test this, so let me give details on my setup and hopefully we can document this to be super easy for nerdy people that want to use Mastodon via CLI. :smile: 

> I did update it with the updated instructions. 

Craig, for the world of me I can't find where those instructions are. Maybe it is a caching issue, but the readme appears the same. Link me, please!

> make sure your are using the latest version of pip. Ubuntu ships with 1.5.4 which won't work because of https.

I am using `pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)`. That seems like a big leap in version numbering, so that looks okay, ne?

**Comment by craigmaloney** [comment]
You should be using Python 3 for Tootstream. That may be why it's not working?

**Comment by craigmaloney** [comment]
And the instructions are right here (on the github page):

https://github.com/magicalraccoon/tootstream

**Comment by craigmaloney** [comment]
Though instead of using python3 setup.py install it should be "pip install tootstream".

**Comment by craigmaloney** [comment]
OK, I updated the README.md with instructions of how to install via pip.

**Comment by maiki** [comment]
So, you still create a virtualenv for the `pip` install?

**Comment by craigmaloney** [comment]
Yeah, that would be preferred. Of course you can install it on your system directly but this is Python. :)

**Comment by maiki** [comment]
> Of course you can install it on your system directly but this is Python.

Shoot, this may be frustrating, but also an opportunity for learning: I don't even know what you mean by that. I have been vaguely aware that python2 and python3 are not the same for what feels like a decade, but that is the amount I grok.

Of course I've been able to successfully use python all the time, and I've used `pip` to install software, but I don't recall even creating a virtualenv to do so, except with web services. So like Mediagoblin, but not all the various apps I use on my laptop.

Is my scenario odd or insecure? I figured I could `pip install tootstream`, and then just use `tootstream` to start it.

Sorry, that sounds so ungrateful! I really do appreciate the work! :smile:

**Comment by craigmaloney** [comment]
The way I've installed things is to use a virtual environment to keep all of the libraries involved in one space. That way it won't try to upgrade the system packages. 

I have a video where I discuss more of how to use virtual environments if you want.

**Comment by craigmaloney** [comment]
Did this work for you?

**Comment by craigmaloney** [comment]
Going to close this for now. If you need additional help please feel free to ping me online and we'll get you set up.

Thanks!
