### ISSUE TITLE
Upgrade to colored 1.3.5

### ISSUE THREAD

**Issue by SirCmpwn** [magicalraccoon/tootstream#142]
And ideally don't pin the version, please.

**Comment by craigmaloney** [comment]
I just took a peek at the latest version of colored (1.3.5) and it looks like the changes are minor. I can update this.

Though I'm curious what prompted this issue? Did something not work or act strange?

Thanks!

**Comment by SirCmpwn** [comment]
When you pin versions and your dependencies update, your software won't work if the package is installed system-wide instead of a virtualenv. Virtualenvs are an anti-pattern.

**Comment by SirCmpwn** [comment]
Better to use >= than ==

**Comment by SirCmpwn** [comment]
Also, click is now on version 6.7.

**Comment by craigmaloney** [comment]
Right, but we've also had instances where updating to Mastodon.py had backward-incompatible changes. So we've done version pinning in order to prevent breakage until we have things sorted.

Anti-pattern or not there's some thought behind both of our reasoning.

**Comment by SirCmpwn** [comment]
I think it'd be better to let it break and have users come around with bug reports. I would also submit your concerns to Mastodon.py. Your other dependencies are a bit more venerable, I wouldn't worry about them.

**Comment by craigmaloney** [comment]
I've updated the requirements.txt and have only pinned Mastodon.py (for now). I think Mastodon 1.1.2 is "just around the corner" (tm) so will test then to see if it causes issues.

Will test this out and may release this proper in 0.3.1 (or 0.4.0, depending on how quickly we can merge profile support).

Thanks!

**Comment by SirCmpwn** [comment]
Thanks!
