### ISSUE TITLE
Add filters to notifications

### ISSUE THREAD

**Issue by maiki** [magicalraccoon/tootstream#146]
I just discovered [the ability to disable certain kinds of notifications in the web UI panel](https://mastodon.sdf.org/@maiki/99066748145070356). That is fantastic, and I'd love to customize the `note` sub-command to also filter notifications.

The main crux is reducing noise, the spirit of which tootstream excels. Let me know what other info is useful. :smile:

**Comment by craigmaloney** [comment]
This was released in 0.3.2. Thanks for the suggestion!
