### ISSUE TITLE
Display URLs for media?

### ISSUE THREAD

**Issue by jfmcbrayer** [magicalraccoon/tootstream#159]
I've noticed that many/most media don't have links displayed. I looked at the code, and apparently this is a TODO? It would be helpful in order to be able to view media in an external browser.

**Comment by craigmaloney** [comment]
Yes, this would be helpful. I find myself having to go to the site to see what a picture or what-not is. I'll see if this might be an easy fix.

**Comment by craigmaloney** [comment]
This is addressed in release 0.3.4, which should release by the end of the month.
