### ISSUE TITLE
Allow displaying link of attachements in posts

### ISSUE THREAD

**Issue by Technowix** [magicalraccoon/tootstream#173]
Since https://github.com/tootsuite/mastodon/pull/6672 there is no more link to attachments in post content. 
So maybe let user know if there is an attachment and allow them to show the URL to it.

**Comment by craigmaloney** [comment]
Will see if #160 addresses this.

**Comment by nightpool** [comment]
dupe of https://github.com/magicalraccoon/tootstream/issues/159

**Comment by craigmaloney** [comment]
This is addressed in release 0.3.4.
