### ISSUE TITLE
Links to media are not interactable

### ISSUE THREAD

**Issue by magicalraccoon** [magicalraccoon/tootstream#18]
Users should be able to click on URLs and be directed to their browser.

**Comment by magicalraccoon** [comment]
I think this might be a client issue, closing for now

**Comment by brrzap** [comment]
some terminals can be configured for this ([urxvt](https://wiki.archlinux.org/index.php/rxvt-unicode#Clickable_URLs) can do it with an extension).

with tootstream's current codebase, a command to launch a url in another window isn't difficult (`open --media-from tootid`?) -- using XDG to launch the user's preferred browser, perhaps.  copy/pasting the link into a browser tab is easier, at least for me.  it would be a nice accessibility feature, though, especially with user-configurable launchers.

actually handling a click in a particular position ... might be doable in the future with a curses-style UI.  (see this related [stackex post](http://stackoverflow.com/a/6848670).)
