### ISSUE TITLE
Renaming a list fails with message `name 'list_supportmastodon' is not defined`

### ISSUE THREAD

**Issue by pla1** [magicalraccoon/tootstream#180]
Hi, 

Running Tootstream version: 0.3.4. 

Renaming a list fails with message `name 'list_supportmastodon' is not defined`

```
[@pla (default)]: listcreate alist
List alist created.
[@pla (default)]: listrename alist blist
name 'list_supportmastodon' is not defined
[@pla (default)]: 
```

Thanks, PLA

**Comment by craigmaloney** [comment]
Ah, that's a simple fix, but not sure why my editor didn't catch it.

It's fixed in https://github.com/magicalraccoon/tootstream/commit/fef1e721e0e6697f67f7a5e3db4ab0a3a909c32f. I'll need to do a proper release soon.

Thanks!
