### ISSUE TITLE
follow always responds to username not found.

### ISSUE THREAD

**Issue by bingen13** [magicalraccoon/tootstream#182]
The follow command always responds with username not found. Example:

follow @yogthos@mastodon.social which is a user that exists, gives username not found.

Likewise, the search command when provided a username (existing and valid or not) always replies nothing.

**Comment by craigmaloney** [comment]
Hello,

Which version of Tootstream are you using? (type "about" after bringing up tootstream).

Thanks!

**Comment by bingen13** [comment]
Version 0.3.5.

**Comment by craigmaloney** [comment]
Hm, I'm able to replicate this as well. Not sure what's going on here, as I'm able to search / view other users. Will have to do some more exploring to see what might be the issue.

**Comment by craigmaloney** [comment]
Looks like this is fixed in Mastodon.py 1.3.1. I'll need to update the requirements and test.

Thanks!

**Comment by craigmaloney** [comment]
Part of the 0.3.6 release.
