### ISSUE TITLE
Boosted toots do not show original author or content

### ISSUE THREAD

**Issue by magicalraccoon** [magicalraccoon/tootstream#19]
Currently boosted toots show up as the users' own.

**Comment by claiire** [comment]
I'd also like to add that they don't actually show the toot either. They show up like

    Claire Cavanaugh @clairec 2017-01-22T20:00:45.268Z
    ♺:0 ♥:0 705199

**Comment by magicalraccoon** [comment]
Hmm, I'll take another look. I think I was working on a solution but got distracted by other issues.

**Comment by claiire** [comment]
Followup: it looks like retoots show the content of the retoot for whatever reason so the title might need to be updated again.
