### ISSUE TITLE
Require Colored 1.3.93 or Relicence as GPLv3

### ISSUE THREAD

**Issue by oct2pus** [magicalraccoon/tootstream#194]
I noticed your code was licensed MIT but you use colored library, which only as of 3 months ago was licenced MIT (specifically under version 1.3.93), but the versions you require can include the GPLv3 versions of colored. You will need to either license under GPLv3 or compatible license to be allowed to use that version of colored or you will need to require 1.3.93 or later.\*

\*you could also just remove colored but frankly thats probably more work than either of the other two options.

**Comment by craigmaloney** [comment]
Thank you. We'll make this more explicit in the next release.

**Comment by craigmaloney** [comment]
This has been addressed in the 0.3.7rc1 release candidate. Thank you.
