### ISSUE TITLE
Unable to connect to eldritch.cafe

### ISSUE THREAD

**Issue by StarlitGhost** [magicalraccoon/tootstream#207]
You can reproduce this without an account, try starting with a fresh --profile and set the instance to eldritch.cafe

tootstream just hangs until you press ctrl+c

I don't know if it's a problem on tootstream or eldritch.cafe's side, but cybre.space and botsin.space both still work fine.

eldritch.cafe did recently update to mastodon 2.8, I'm not sure what version the other two are on.

**Comment by craigmaloney** [comment]
This appears to have resolved in the interim. Closing. (And apologies for not noticing this sooner. Thanks!)
