### ISSUE TITLE
Update for Mastodon.py 1.5.0 / Mastodon 3.0

### ISSUE THREAD

**Issue by craigmaloney** [magicalraccoon/tootstream#214]
Need latest Mastodon.py to be compatible with Mastodon 3.0 servers.

**Comment by grondinm** [comment]
Should this not be closed now?

https://github.com/magicalraccoon/tootstream/commit/fc845a53820680053b936e534a6096d7844626b0

Unless something else is missing in which case please ignore me...

**Comment by craigmaloney** [comment]
Eep. Looks like it. Thanks!
