### ISSUE TITLE
Could not complete request: Connection aborted.

### ISSUE THREAD

**Issue by johnpiers** [magicalraccoon/tootstream#229]
"Could not complete request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

I cannot remember this thing (tootstream) doing this before. So forgive me if this is normal behaviour, I doubt that it is, please correct me if I'm wrong.  The above message is what happens when 'tootstream' stands idle for a few minutes. If you re-issue the command it refreshes as expected. 

I have looked through the issues and I've not seen anything related.

Many thanks,
JohnPiers

**Comment by craigmaloney** [comment]
That appears to be a timeout on your server's side. Not much for us to do in that case other than for it to be retried once the server is back up.

Hope this helps!
