### ISSUE TITLE
Simplify posting local media

### ISSUE THREAD

**Issue by magicalraccoon** [magicalraccoon/tootstream#24]
I'm not sure if there's going to be a way to upload pictures via tootstream, but it would be a nice feature.

**Comment by brrzap** [comment]
[Mastodon.media_post()](http://mastodonpy.readthedocs.io/en/latest/#writing-data-media) coupled with [Mastodon.status_post()](http://mastodonpy.readthedocs.io/en/latest/#writing-data-statuses) should do it.

**Comment by brrzap** [comment]
implemented in experimental with options on toot/reply commands.  see [exp/74bf2b1](https://github.com/brrzap/tootstream/commit/74bf2b17c5d1e91c2d271671c79db2b24b8690b1) (`toot`) and [exp/0267d32](https://github.com/brrzap/tootstream/commit/0267d3234fe7abd717f31ce596a02457f98d8ac2) (`reply`).

the resulting commands look something like:

    [@user]: toot -m file1 -m file2 -m file3 --nsfw --vis unlisted --spoiler 'my spoiler text' hello world
    
    [@user]: reply -m file1 -m file2 --nsfw --vis private --spoiler 'changing spoiler text' 123456 hello back

an interactive mode could be offered as well -- either prompts for each option or popping open your favorite editor a la git.

the logic is pretty straightforward but reading options like that out of `rest` is a pain.  if this style of commandline is what you have in mind, consider Click or another framework for the heavy lifting.

**Comment by magicalraccoon** [comment]
Interactive would be great but I'm also okay with not including media uploading

**Comment by brrzap** [comment]
UI sketch for a short-option alternative: using flags to activate prompts for filenames.  could look something like this:

    [@user]: toot -m Hello World!                 # "Hello World" accepted as toot content
    You can attach up to 4 files.
    add file 1: ~/foo.png                         # tab completion? confirm readable?
    add file 2: /path/to/another/file.jpg
    add file 3:                                   # recognize blank as end of file list
    Attaching files:  1: /full/path/to/foo.png    # print list as confirmation to user
                      2: /path/to/another/file.jpg
    Mark sensitive [y/N]: Y                       # offer to mark NSFW (blank defaults to No?)
    # Ctrl-C at any point above should cancel back to prompt (no send)
    # post and print usual success/error msg here

an `-n` flag could change the default at the sensitivity prompt (but should still prompt).  `-n` without `-m` can be ignored.  similar flags (`-c`, `-v`) can be used to trigger prompts for spoiler text and post visibility.  flags can be specified individually or together (`-m -c -v` same as `-mcv`).

**Comment by craigmaloney** [comment]
This was implemented with @brrzap 's pull request for Content Warning / Privacy / Media. Thank you so much!
