### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by charliegreen** [magicalraccoon/tootstream#25]
Hello! I ran the commands in the readme, then ran the script and got ImportErrors for `click` and `mastodon`. This was easy enough to fix with `pip install click` and `pip install Mastodon.py` (I assume this is the right mastodon module? It seems to be working, at any rate), but the point is this didn't happen automatically. The end of setup.py's output may be relevant:

```
Searching for pkg-resources==0.0.0
Reading https://pypi.python.org/simple/pkg-resources/
No local packages or working download links found for pkg-resources==0.0.0
error: Could not find suitable distribution for Requirement.parse('pkg-resources==0.0.0')
```

After only installing `click` and `mastodon`, though, tootstream seems to work just fine. But I thought I'd open an issue anyway, just to let you know.

**Comment by bottitytto** [comment]
I also had to do this to use tootstream.

**Comment by mccolgst** [comment]
This should be fixed now as the above mentioned pull request was merged. Thanks!
