### ISSUE TITLE
Two-factor authentication is not supported

### ISSUE THREAD

**Issue by elopio** [magicalraccoon/tootstream#31]
I was trying to login and was puzzled why it wasn't accepting my credentials. After more tries than I am proud to admit, I thought that the problem might be the two-factor authentication that I enabled in my mastodon account.

I disabled 2FA, and I could log in.

Short term solution would be to show a nice error when an account is requesting 2FA. Then, it would be great to support it. We are living scary days.

Thanks for your work!

**Comment by magicalraccoon** [comment]
I'll make a not of it at the login screen until I get it working, thanks!
