### ISSUE TITLE
help beautification project

### ISSUE THREAD

**Issue by brrzap** [magicalraccoon/tootstream#47]
wishlist

- [x] prettier, consistent help text for commandline options (#48)
- [x] short options where expected (`-h` vs `--help`) (#48)
- [ ] prettier, consistent help text for REPL commands and their arguments

**Comment by brrzap** [comment]
i think the last one is good to go now (clean columns and help for specific commands).  wording and examples can be changed as necessary, but the mechanism is in place.  does anything else need to be done under this umbrella, or should it be closed out?

**Comment by magicalraccoon** [comment]
That should do it. Closing.
