### ISSUE TITLE
Error: "No module named 'click'"

### ISSUE THREAD

**Issue by nevillepark** [magicalraccoon/tootstream#52]
After installation, when I try to launch tootstream with ```python3 tootstream/toot.py```, I get this error:

```
Traceback (most recent call last):
  File "tootstream/toot.py", line 2, in <module>
    import click
ImportError: No module named 'click'
```

**Comment by brrzap** [comment]
sounds like you missed a step while installing.  did you run the `python3 setup.py install` command in the root of your cloned repo?  

in the README, i think Step 2's `cd` command is extraneous -- potentially confusing if you're running through the steps verbatim.

**Comment by magicalraccoon** [comment]
Looks like a user error.
