### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jadykes** [magicalraccoon/tootstream#54]
Hi, I'm not particularly git-savvy yet.
Followed install procedure from here at git page. 
Upon python3 setup.py install, this was returned.

Installed /home/user/tootstream/tootstream/lib/python3.5/site-packages/tootstream-0.1-py3.5.egg
Processing dependencies for tootstream==0.1
Searching for readline==6.2.4.1
Reading https://pypi.python.org/simple/readline/
Downloading https://pypi.python.org/packages/f4/01/2cf081af8d880b4stuffa5f1b446551a7f8d59eae41stufffd0c303757ff1b/readline-6.2.4.1.tar.gz#md5=578237939c81fdbc2c8334d168b17907
Best match: readline 6.2.4.1
Processing readline-6.2.4.1.tar.gz
Writing /tmp/easy_install-y773bjdl/readline-6.2.4.1/setup.cfg
Running readline-6.2.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y773bjdl/readline-6.2.4.1/egg-dist-tmp-4hkr5cya
Modules/3.x/readline.c: In function ‘PyInit_readline’:
Modules/3.x/readline.c:1179:34: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     PyOS_ReadlineFunctionPointer = call_readline;
                                  ^
/usr/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
 
Since other succeeded where this failed, I'm suspecting I'm missing a package. 
Error occurred on Ubuntu 16.04LTS.

**Comment by brrzap** [comment]
You probably need the `libncurses5-dev` package.

An Ubuntu 16.04.2 livecd environment needs this command to pull all the dependencies:

    sudo apt-get install python3-dev virtualenv libreadline6-dev libncurses5-dev

**Comment by jadykes** [comment]
Ah, those were the key. I was able to finish setup and run tootstream!
