### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by booyaa** [magicalraccoon/tootstream#59]
for commands e.g. `pub<tab>` becomes `public`
for handle completion in mentions e.g. `@booy<tab>` becomes `@booyaa`

for handle completion, the scope could be simplified by only completing names of people you follow.

**Comment by magicalraccoon** [comment]
Tab completion would be super nice to have, but I'd have to look up how to implement it.

**Comment by claiire** [comment]
I'll try my hand at this? :D

**Comment by magicalraccoon** [comment]
Added in #107
