### ISSUE TITLE
Translation services

### ISSUE THREAD

**Issue by booyaa** [magicalraccoon/tootstream#72]
I'm not sure how this would work, but it would be nice to automatically translate toots. 

I appreciate machine translation is still terrible.

e.g. How this might look in-line

```  
poem.exe @poem_exe@botsin.space 2017-04-20T08:21:02.000Z
  ♺:1 ♥:0 id:14
  fresh strawberry
  the teacup's curve
  drips from the roof
  fresh strawberry
__
Fraise fraise
   La courbe de la tasse à thé
   Gouttes du toit
   Fraise fraise
```

The downside is that this would increase the size of toot. Also depending on the translation service, you'd probably go over the rate limit in no time.

An alternative might be to create a new command called `translate` which accepts an `id` of a toot to translate:

```
[@booyaa]: translate 14
translated toot:
poem.exe @poem_exe@botsin.space 2017-04-20T08:21:02.000Z
  ♺:1 ♥:0 id:14

Fraise fraise
   La courbe de la tasse à thé
   Gouttes du toit
   Fraise fraise
```

The downside is an additional action, but given that the birdsite still requires you to click the translate link this is maybe a feature. It would also avoid exceeding rate limit for a translation service.

If this is exceeding the purpose of `tootstream`, could we have a way to create plugins to extend functionality?

**Comment by magicalraccoon** [comment]
I don't think translation is within the current scope of this project, but if someone wants to work on it I wouldn't mind including it.
