### ISSUE TITLE
Set toot time to a more readable format

### ISSUE THREAD

**Issue by magicalraccoon** [magicalraccoon/tootstream#87]
The current format is `2017-05-03T09:58:28.473Z`, but we could go two ways: relative time (10 minutes ago), or a natural time (9:58pm) or (21:58). Rainbowstream's format is `2017/05/03 03:22:32` but I wonder if that's too much information for only displaying a few toots at a time. Thoughts?

**Comment by brrzap** [comment]
personally i like having the real timestamp shown; the relative time is nice but isn't terribly useful 10 minutes later.

this [was broached](https://github.com/brrzap/tootstream/issues/4) in experimental and the `arrow` package was suggested for relative times (https://github.com/brrzap/tootstream/commit/db11ac48835a12dff1bea943489b30439413b63c).  i later added a `strftime` version to prettify the regular timestamp (https://github.com/brrzap/tootstream/commit/294d7e27563f30b7575ad0a412b7ad445011ff73).  the output looks like:

    2017.05.03 10:19 UTC (17 minutes ago)

`arrow` is probably a little overkill for this use, but it was pretty easy to drop in and let it run, and if i ever get around to converting that timestamp to the user's locale it'll handle that too.

**Comment by craigmaloney** [comment]
This was added with #137.
